### PR TITLE
Change two logs to severity debug

### PR DESCRIPTION
**Pull request by DanielWeeber**
Change logmessages "All Nut values set" and "Start NUT update" to severity debug, as this cludders the info log and is not necessary.

### CODE REVIEW

**Comment by Apollon77** [comment]
Hm ... will think of it. Was by intent ...

You can set the loglevel for the specific adapter instance to warn and the messages will disappear from the log ;-) (expert mode at instances in admin)

**Comment by Apollon77** [comment]
also fixes #11

**Comment by Apollon77** [comment]
But new release will need some days!

**Comment by DanielWeeber** [comment]
Please release the new version

**Comment by Apollon77** [comment]
Yes, Install from GitHub in the meantime please

**Pull request merged**
